apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: jellyfin
description: jellyfin helm chart for Kubernetes
type: application
version: 2.1.1
# image: jellyfin/jellyfin
appVersion: "10.11.5"
maintainers:
  - name: Joe Harrison
    email: sudo-kraken@prxy.8shield.net
sources:
  - https://github.com/sudo-kraken/helm-charts/tree/main/charts/jellyfin
home: https://github.com/jellyfin/jellyfin
icon: https://artifacthub.io/image/08745b60-3c38-4642-af66-7d51aec43b9f@4x
