apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: prowlarr
description: prowlarr helm chart for Kubernetes
type: application
version: 3.1.3
# image: ghcr.io/home-operations/prowlarr
appVersion: "2.1.5"
maintainers:
  - name: Joe Harrison
    email: sudo-kraken@prxy.8shield.net
sources:
  - https://github.com/sudo-kraken/helm-charts/tree/main/charts/prowlarr
home: https://github.com/prowlarr/prowlarr
icon: https://artifacthub.io/image/08745b60-3c38-4642-af66-7d51aec43b9f@4x
